### ISSUE TITLE
브랜치 생성 관련 사항

### ISSUE THREAD

**Issue by bori1106** [coworkcarrot/seedcollab#15]
계속 시도해봤으나 아무래도 저한테 브랜치를 생성할 수 있는 권한이 없는 것 같습니다.
저는 Sourcetree 이용하고 있는데 깃허브에서도, Sourcetree에서도 브랜치 생성이 안되네요...
그래서 일단 제 계정에 올려두었습니다! 내일 만나서 브랜치 생성하고 코드 정리 후에 깃허브에서 바로 merge하면 될 것 같아요.

https://github.com/bori1106/github-test2

**Comment by hyunji1117** [comment]
해당 부분 write 권한 부여로 해결 check 합니다!
